name: Build and Run App

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Install deps
        run: |
          apt update -y
          apt install nodejs git ca-certificates curl gnupg lsb-release -y
          mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
          apt update -y
          apt install docker-ce -y          
      
      - name: Removing old docker image and container
        run: |
          docker stop instagram_frontend || true
          docker rm instagram_frontend || true
          docker rmi instagram_frontend_image || true          
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the image
        run: |
          docker build -t frontend_image .          
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

      - name: Run the image
        run: |
          docker run -d --name instagram_frontend -p 80:80 instagram_frontend_image          
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
